# Generated by Django 5.1.6 on 2025-02-21 10:39

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce", "0002_alter_order_payment_method_orderline"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="e_commerce.city",
                verbose_name="User City",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="e_commerce.country",
                verbose_name="User Country",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="type_user",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "Client"),
                    ("G", "Gestionnaire"),
                    ("A", "Administrateur"),
                ],
                default="C",
                max_length=1,
                verbose_name="type user",
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="city",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="e_commerce.city",
                verbose_name="User City",
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="country",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="e_commerce.country",
                verbose_name="User Country",
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="type_user",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "Client"),
                    ("G", "Gestionnaire"),
                    ("A", "Administrateur"),
                ],
                default="C",
                max_length=1,
                verbose_name="type user",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalStockMovement",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="Unique Identifier",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Creation Timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Last Update Timestamp"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("IN", "Entrée"), ("OUT", "Sortie")],
                        max_length=3,
                        verbose_name="Type de mouvement",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Raison du mouvement de stock (ex: réapprovisionnement, vente, retour, etc.)",
                        max_length=200,
                        verbose_name="Motif",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date du mouvement"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de commande, bon de livraison, etc.",
                        max_length=50,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="e_commerce.product",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical stock movement",
                "verbose_name_plural": "historical stock movements",
                "db_table": "StockMovement_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Unique Identifier",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Update Timestamp"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("IN", "Entrée"), ("OUT", "Sortie")],
                        max_length=3,
                        verbose_name="Type de mouvement",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Raison du mouvement de stock (ex: réapprovisionnement, vente, retour, etc.)",
                        max_length=200,
                        verbose_name="Motif",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date du mouvement"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de commande, bon de livraison, etc.",
                        max_length=50,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="e_commerce.product",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
