# Generated by Django 5.1.6 on 2025-02-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce", "0003_customuser_city_customuser_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockmovement",
            name="product",
        ),
        migrations.DeleteModel(
            name="HistoricalStockMovement",
        ),
        migrations.DeleteModel(
            name="StockMovement",
        ),
    ]
